version: "3.9"

services:
  app:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

networks:
  default:
    driver: bridge
